name: Auto Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      run: |
        # 使用 corepack 确保 pnpm 版本一致性
        corepack enable
        corepack prepare pnpm@9.15.4 --activate

    - name: Install dependencies
      run: |
        pnpm install
        pnpm add -D pkg

    - name: Clean cache (强制刷新)
      run: |
        pnpm store prune
        rm -rf node_modules
        pnpm cache clean --force

    - name: Build project
      run: node build.js
      env:
        NODE_OPTIONS: '--experimental-vm-modules'
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: Release ${{ env.CONVERTED_VERSION }}
        files: |
          dist/index_${{ env.CONVERTED_VERSION }}.exe
          dist/index_${{ env.CONVERTED_VERSION }}.zip
        draft: true
