name: Auto Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      custom_version:
        description: 'Manual version (格式：vx.x.x)'
        required: false
        default: ''

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Resolve version
      id: version
      run: |
        if [ -n "${{ inputs.custom_version }}" ]; then
          RAW_VERSION="${{ inputs.custom_version}}"
        else
          RAW_VERSION=$(git describe --tags --abbrev=0)
        fi

        # 移除v前缀并转换格式：v2.0.0 → 2_0_0
        CLEAN_VERSION=${RAW_VERSION#v}
        CONVERTED_VERSION=$(echo "$CLEAN_VERSION" | sed 's/\./_/g')
        
        echo "RAW_VERSION=$RAW_VERSION" >> $GITHUB_ENV
        echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
        echo "CONVERTED_VERSION=$CONVERTED_VERSION" >> $GITHUB_ENV

    - name: Build project
      run: node build.js
      env:
        NODE_OPTIONS: '--experimental-vm-modules'
        BUILD_VERSION: ${{ env.CLEAN_VERSION }}  # 传递给构建脚本的是 2.0.0

    - name: Verify artifacts
      run: |
        ls -lh dist/
        [ -f dist/index_${{ env.CONVERTED_VERSION }}.exe ] || exit 1
        [ -f dist/index_${{ env.CONVERTED_VERSION }}.zip ] || exit 1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RAW_VERSION }}
        name: Release ${{ env.CONVERTED_VERSION }}
        files: |
          dist/index_${{ env.CONVERTED_VERSION }}.exe
          dist/index_${{ env.CONVERTED_VERSION }}.zip
        draft: true
        body: "自动生成的预览版，请检查后发布"
