name: Auto Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      custom_version:
        description: 'Manual version (格式：vx.x.x)'
        required: false
        default: ''

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm@9

    - name: Install dependencies
      run: |
        pnpm install
        pnpm add -g pkg

    - name: Convert version format
      id: version
      run: |
        if [ -n "${{ inputs.custom_version }}" ]; then
          VERSION_TAG="${{ inputs.custom_version}}"
        else
          VERSION_TAG=$(git describe --tags --abbrev=0)
        fi
        
        # 转换 v1.2.3 → v_1_2_3
        CONVERTED_VERSION=$(echo "$VERSION_TAG" | sed 's/\./_/g')
        echo "VERSION=${VERSION_TAG#v}" >> $GITHUB_ENV
        echo "CONVERTED_VERSION=$CONVERTED_VERSION" >> $GITHUB_ENV
        echo "Tag Version: $VERSION_TAG"
        echo "Converted Version: $CONVERTED_VERSION"

    - name: Build project
      run: node build.js
      env:
        NODE_OPTIONS: '--experimental-vm-modules'

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: Release ${{ env.CONVERTED_VERSION }}
        files: |
          dist/index_${{ env.CONVERTED_VERSION }}.exe
          dist/index_${{ env.CONVERTED_VERSION }}.zip
        draft: true
