name: Auto Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      custom_version:
        description: 'Manual version (格式：vx.x.x)'
        required: false
        default: ''

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci  # 使用严格依赖版本

    - name: Resolve version
      id: version
      run: |
        if [ -n "${{ inputs.custom_version }}" ]; then
          VERSION_TAG="${{ inputs.custom_version}}"
        else
          VERSION_TAG=$(git describe --tags --abbrev=0)
        fi
        
        # 转换 v1.2.3 → v_1_2_3
        CONVERTED_VERSION=$(echo "$VERSION_TAG" | sed 's/\./_/g')
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
        echo "CONVERTED_VERSION=$CONVERTED_VERSION" >> $GITHUB_ENV
        echo "BUILD_VERSION=${VERSION_TAG#v}" >> $GITHUB_ENV

    - name: Build project
      run: node build.js
      env:
        NODE_OPTIONS: '--experimental-vm-modules'
        BUILD_VERSION: ${{ env.BUILD_VERSION }}

    - name: Verify artifacts
      run: |
        ls -lh dist/
        [ -f dist/index_${{ env.CONVERTED_VERSION }}.exe ] || exit 1
        [ -f dist/index_${{ env.CONVERTED_VERSION }}.zip ] || exit 1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: Release ${{ env.CONVERTED_VERSION }}
        files: |
          dist/index_${{ env.CONVERTED_VERSION }}.exe
          dist/index_${{ env.CONVERTED_VERSION }}.zip
        draft: true
        body: "自动生成的预览版，请检查后发布"
